config path is /fate/examples/hetero_secureboosting_tree/conf/guest_runtime_conf.json_secureboosting_example_standalone_20190803131023
jobid is secureboosting_example_standalone_20190803131023
fail to post status running
Finish encrypt parameter check!
Finish evaluation parameter check!
Finish predict parameter check!
Finish predict parameter check!
Finish evaluation parameter check!
Finish workerflow parameter check!
Finish init parameter check!
Finish encode parameter check!
Finish encode parameter check!
Finish intersect parameter check!
Finish init parameter check!
Finish encrypt parameter check!
Finish logistic parameter check!
Finish encrypt parameter check!
Finish scale parameter check!
Finish one_vs_rest parameter check!
Finish all parameter checkers
Get in base workflow initialize
Finish encrypt parameter check!
Finish predict parameter check!
Finish evaluation parameter check!
Finish workerflow parameter check!
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\uff0c' in position 62: ordinal not in range(128)
Call stack:
  File "../../workflow/hetero_secureboosting_tree_workflow/hetero_secureboosting_tree_guest_workflow.py", line 46, in <module>
    workflow.run()
  File "/fate/workflow/status_tracer_decorator.py", line 69, in wrapper
    res = func(self, *args, **kwargs)
  File "/fate/workflow/workflow.py", line 906, in run
    self.cross_validation(data_instance)
  File "/fate/workflow/workflow.py", line 554, in cross_validation
    eval_name, mean_value, std_value))
Message: 'guest\uff0cevaluate name: auc, mean: 0.9459, std: 0.0177'
Arguments: ()
