"2019-08-24 09:16:15,499 - status_tracer_decorator.py[line:73] - INFO: job status is failed"
"2019-08-24 09:16:15,500 - status_tracer_decorator.py[line:74] - INFO: Traceback (most recent call last):
  File "/fate/workflow/status_tracer_decorator.py", line 69, in wrapper
    res = func(self, *args, **kwargs)
  File "/fate/workflow/workflow.py", line 920, in run
    self.network_embedding(data_instances, node2id, local_instances, common_nodes)
  File "/fate/workflow/workflow.py", line 216, in network_embedding
    self.nrler.fit(data_instances, node2id, local_instances, common_nodes)
  File "/fate/federatedml/network_embedding/hetero_network_embedding/hetero_ne_host.py", line 113, in fit
    batch_num += 1
UnboundLocalError: local variable 'batch_num' referenced before assignment
"
"2019-08-24 09:16:15,503 - status_tracer_decorator.py[line:59] - INFO: fail to post status failed"
