"2019-08-22 08:17:16,879 - status_tracer_decorator.py[line:73] - INFO: job status is failed"
"2019-08-22 08:17:16,879 - status_tracer_decorator.py[line:74] - INFO: Traceback (most recent call last):
  File "/fate/workflow/status_tracer_decorator.py", line 69, in wrapper
    res = func(self, *args, **kwargs)
  File "/fate/workflow/workflow.py", line 913, in run
    self.network_embedding(data_instances, node2id)
  File "/fate/workflow/workflow.py", line 215, in network_embedding
    self.nrler.fit(data_instances, node2id)
  File "/fate/federatedml/network_embedding/hetero_network_embedding/hetero_ne_guest.py", line 194, in fit
    idx=0)
  File "/fate/arch/api/federation.py", line 73, in remote
    return RuntimeInstance.FEDERATION.remote(obj=obj, name=name, tag=tag, role=role, idx=idx)
  File "/fate/arch/api/standalone/federation.py", line 102, in remote
    raise ValueError("{} cannot be None if idx specified".format(role))
ValueError: None cannot be None if idx specified
"
"2019-08-22 08:17:16,882 - status_tracer_decorator.py[line:59] - INFO: fail to post status failed"
